# Generated by Django 5.2 on 2025-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=32, null=True)),
                ('release_date', models.DateField(null=True)),
                ('genre', models.CharField(max_length=16, null=True)),
                ('songs_quantitty', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
